### ISSUE TITLE
error: '"None of [Index([''sequence'', ''score'', ''decoy''], dtype=''object'')] are   in the [columns]"'

### ISSUE THREAD

**Issue by Maithy15** [MannLabs/alphapept#308]
**Describe the bug**
Error - 1
I am getting the following error - error: '"None of [Index([''sequence'', ''score'', ''decoy''], dtype=''object'')] are
  in the [columns]"'

I am trying to analyze some Bruker Impact II QTOF data. Does alphapept only process timstof data or data from other Bruker TOFs?

Error-2
I am also getting the following error in the results tab

AttributeError: 'DataFrame' object has no attribute 'px_fit_results'
Traceback:
File "streamlit\script_runner.py", line 337, in _run_script
    exec(code, module.__dict__)
File "C:\Program Files (x86)\AlphaPept\alphapept\webui.py", line 46, in <module>
    sidebar[menu]()
File "alphapept\gui\results.py", line 331, in results
    parse_file_and_display(file)
File "alphapept\gui\results.py", line 231, in parse_file_and_display
    scatter_plot(file, options)
File "alphapept\gui\results.py", line 209, in scatter_plot
    st.code(results.px_fit_results.iloc[0].summary())
File "pandas\core\generic.py", line 5462, in __getattr__
    return object.__getattribute__(self, name)

**Version (please complete the following information):**
 - OS: Windows 10 Enterprise N
 - Version 0.3.26
 - Installation Type - One-Click Installer

**Comment by straussmaximilian** [comment]
Hi,
thanks for reporting.
So far, only timsTOF data tested. Do you mind sharing a file so the pipeline can be tested?

**Comment by Maithy15** [comment]
Hi,
Thanks for the reply. Please find the zip folder here (https://fz-juelich.sciebo.de/s/mScfGdyrQgV8z4w) containing two impact-II .d files. These are DDA shotgun runs of trypsin digested Arabidopsis leaf proteome (120 min run with 90 mins of effective separation). Please let me know if you need more info or measurements from other organisms.

**Comment by straussmaximilian** [comment]
Hi,
Thanks for uploading the dataset - I was now able to investigate a little bit more. The file type is `.baf` and would require another Bruker sdk to be read. Apparently, the `.baf` filetype will be replaced by `.tsf`-format. Feature finding on these files with the Bruker feature finder seems to work, however, it produces an mgf file.
For now, there will be no support for QTOF data unless an external contributor steps in (Happy to guide through the codebase in case). Nevertheless, feel free to upvote on the discussions page so that we can track what features are considered relevant by the community: https://github.com/MannLabs/alphapept/discussions/314. If this will be requested by a lot of people, we can potentially prioritize it.
I will also note this on the compatibility in the Readme.
Thanks.
