### ISSUE TITLE
Difficulty in getting any results in any experiment, even with the provided sample run

### ISSUE THREAD

**Issue by fierytortilla** [MannLabs/alphapept#354]
I have recently downloaded and starting using alphapept v 0.3.29 and have been having difficulty trying to get it to work. I set it up on my personal Macbook (OSX 10.14 Mojave and 2.5 GHz Intel Core i5) using the Python set up instructions from the README.MD file. All the experiments that I start do complete, but they never have any results to display. So, I decided to use the sample run from the Start page (using the irtfusion.fasta and 20200911_EXPL0_IgPa_6min_DDA_2.raw), but this leads to the same result, where no results can be found. Is there some step that I am missing in order to get this program to work? I have looked through the logs of the different tests I have conducted with the sample run, and I think the problem may lie with the Python module `clr`, since I have identified two errors that mention it: `File conversion of file 20200911_EXPL0_IgPa_6min_DDA_2.raw failed. Exception No module named 'clr'`. I have tried to download it using `python -m pip install clr`, but this error instead became: `File conversion of file 20200911_EXPL0_IgPa_6min_DDA_2.raw failed. Exception module 'clr' has no attribute 'AddReference'`. 

Moreover, after the `clr` related errors, I have found the error in all logs: `Feature finding of file 20200911_EXPL0_IgPa_6min_DDA_2.raw failed. Exception "Group Raw/MS1_scans does not exist in <HDF_File 20200911_EXPL0_IgPa_6min_DDA_2.ms_data.hdf>. Error 'Unable to open object (component not found)'"`. I suspect this is a result of the `clr` module not working, but I'm uncertain. Any help would be most appreciated.

**To Reproduce**
1. Run `alphapept gui` in Terminal.
2. Get the .fasta and .raw file from the Start tab of GUI, place in a folder of choice.
3. Go to New Experiment tab and set up New Experiment. Load folder of choice with the sample run, and then run the experiment with default workflow and settings (i.e. don't modify either part).
4. After a few seconds, the experiment completes, and no results are found.

**Screenshots**
![image](https://user-images.githubusercontent.com/29728677/136205390-f78239fb-41be-4baa-bf46-efdab3426e55.png)

**Comment by jalew188** [comment]
Hi @fierytortilla , it is because the `pythonnet` package is not correctly installed. Please follow https://github.com/MannLabs/alphapept#mac to install `pythonnet`. If it does not work, there may be two reasons.

1. `mono` is not correctly installed, we don't know how to fix it then.
2. Type `where mono` (you may get mono path `/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono`), then follow item `3` in https://github.com/MannLabs/alphapept#mac to config mono pkgconfig path (mono pkgconfig path should be `/Library/Frameworks/Mono.framework/Versions/Current/lib/pkgconfig`), and then 'pip install pythonnet'
