### ISSUE TITLE
StreamLitAPIException - GUI

### ISSUE THREAD

**Issue by brvpuyve** [MannLabs/alphapept#374]
Hi AlphaPept team, 

Yesterday, I installed the 0.3.29 GUI version to process some Thermo Orbitrap .raw and Sciex .mzML files. Unfortunately, for both datasets, I am receiving the same error (image in attachment). It does seem that there is some output, but I assume this will be incomplete. Any idea what the issue could be? I was thinking of language settings (Dutch - AZERTY) but I am not an expert!

Thanks for the help!

Bart

[2021_12_06_DDA_Orbitrap.log](https://github.com/MannLabs/alphapept/files/7668721/2021_12_06_DDA_Orbitrap.log)

![issue_alphapept](https://user-images.githubusercontent.com/35368580/145038633-096f4b13-5427-4a42-a06f-e4a107220844.PNG)

**Comment by straussmaximilian** [comment]
Hi, 
Thanks for reporting. The Error itself is a display bug. The progress bar got a value that is larger than what it can display (i.e.,> 1). The error should disappear if you refresh the page at a later stage.
Judging from the log, the experiment did run through.

The underlying error should be fixed in 0.3.30; I will upload a new installer alter today.
